language: java

# Ubuntu 16.04. Lastest available Linux as of 2019-05-07.
dist: xenial
# Disabling sudo routes the build to a Docker container instead of a VM
# which speeds up the build.
sudo: false

addons:
  apt:
    packages:
    - ant
    - ant-optional
    - junit4
    - libhamcrest-java
    # For .travis.upload-jar-to-freenet.sh
    - python3-pip
  # TODO: Code quality: Remove this workaround for https://github.com/travis-ci/travis-ci/issues/5227
  hosts:
    - freenet-plugin-Freetalk
  hostname: freenet-plugin-Freetalk

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f  $HOME/.gradle/caches/jars-2/jars-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  apt: true
  directories:
  - $TRAVIS_BUILD_DIR/../fred/
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
  - cd "$TRAVIS_BUILD_DIR"/..
  - if [ ! -e fred/src ]; then git clone https://github.com/freenet/fred.git --branch next --single-branch --depth 1 fred ; else cd fred ; git pull ; cd .. ; fi
  - cd fred
  - echo -e "org.gradle.parallel = true\norg.gradle.jvmargs=-Xms256m -Xmx1024m\norg.gradle.configureondemand=true\ntasks.withType(Test) {\n maxParallelForks = Runtime.runtime.availableProcessors()\n}" > gradle.properties
  # The gradlew binary which fred ships doesn't work on OpenJDK 7, need to use Travis' gradle there.
  - if [ "$TRAVIS_JDK_VERSION" = "openjdk7" ] ; then rm ./gradlew && ln -s "$(which gradle)" ./gradlew ; fi
  # TODO: freenet.jar won't contain class Version if we don't run the
  # clean task in a separate execution of Gradle. Why?
  - ./gradlew clean
  # "copyRuntimeLibs" copies the JAR *and* dependencies - which Freetalk also
  # needs - to build/output/
  - ./gradlew jar copyRuntimeLibs -x test
  - cd "$TRAVIS_BUILD_DIR"

script:
  - set -o errexit
  - echo 'Checksums of dependencies:' ; sha256sum ../fred/build/output/*
  - echo 'fred version:' ; java -classpath '../fred/build/output/freenet.jar' 'freenet.node.Version'
  - ant

jdk:
  # openjdk7: Not available anymore.
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  # oraclejdk7: Not supported anymore: https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879
  # oraclejdk8: Not available anymore.
  # oraclejdk9: No more updates by Oracle: https://www.oracle.com/technetwork/java/java-se-support-roadmap.html
  # oraclejdk10: Not supported anymore: https://changelog.travis-ci.com/stop-a-job-early-if-a-deprecated-jdk-is-configured-76612
  - oraclejdk11
  # oraclejdk12: Not available yet on Travis CI as of 2019-05-07, was released 2019-03.

# FIXME: Adapt to Freetalk and enable
# deploy:
#   provider: script
#   # Prevent Travis from deleting the JAR before we can deploy it (wtf?)
#   skip_cleanup: true
#   script: ./.travis.upload-jar-to-freenet.sh
#   on:
#     all_branches: true
