name: CI cronjobs

# FIXME: Add these cronjobs:
# - Weekly CI run on branches next and master
# - Daily CI run on branch master IF branch next of fred changed.

on:
  schedule:
    # FIXME: For debugging this runs every 5 minutes. Decrease a lot once finished!
    - cron: 0/5 * * * *

jobs:
  run-ci-workflow:
    name: Weekly CI workflow on xor-freenet's repo only
    # FIXME: Remove testing code "-DO-NOT-USE" after testing
    if: github.repository == 'xor-freenet/plugin-Freetalk-DO-NOT-USE'
    uses: ./.github/workflows/gradle.yml
