name: CI cronjobs

# FIXME: Add these cronjobs:
# - Weekly CI run on branches next and master
# - Daily CI run on branch master IF branch next of fred changed.

on:
  schedule:
    # ATTENTION: When changing these, you MUST also change the other occurences in the file!
    - cron: 12 18 * * 1 # At 18:12 on Monday
    # FIXME: For debugging this runs every 5 minutes. Decrease a lot once finished!
    - cron: 0/5 * * * *

jobs:
  weekly-ci-workflow:
    name: Weekly CI workflow, on xor-freenet's repo only
    if: |
      github.event.schedule == '12 18 * * 1'
      && github.repository == 'xor-freenet/plugin-Freetalk'
    uses: ./.github/workflows/gradle.yml

  run-ci-workflow-if-fred-changed:
    name: Daily CI workflow if fred changed, on xor-freenet's repo only
    # FIXME: Remove testing code "-DO-NOT-USE" after testing
    if: |
      github.event.schedule == '0/5 * * * *'
      && github.repository == 'xor-freenet/plugin-Freetalk-DO-NOT-USE'
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Get previous and current fred branch next HEAD revision
      shell: bash
      run: |
        set -o errexit
        
        echo 'Previous HEAD of fred branch next:'
        # FIXME: Cache the file!
        if [ -f previous_fred_next_revision ] ; then
            cat previous_fred_next_revision
        else
           echo 'NONE' | tee previous_fred_next_revision
        fi
        
        echo 'Current HEAD of fred branch next:'
        git ls-remote 'https://github.com/freenet/fred.git' \
          | awk '/refs[/]heads[/]next/ {print $1}' \
          | tee current_fred_next_revision
    
    - name: Checkout Freetalk git repository
      if: hashFiles('current_fred_next_revision') != hashFiles('previous_fred_next_revision')
      uses: actions/checkout@v2 # The below step errors if we don't check out the git repo here.
      with:
        # We must use a subdir so the *_fred_next_revision files aren't deleted by the checkout.
        path: plugin-Freetalk
    
    - name: FIXME - Debug code for the next step
      shell: bash
      run: |
       stat '/home/runner/work/plugin-Freetalk-DO-NOT-USE/plugin-Freetalk-DO-NOT-USE/plugin-Freetalk/.github/workflows/gradle.yml'
    
    - name: Run CI workflow if fred changed
      if: hashFiles('current_fred_next_revision') != hashFiles('previous_fred_next_revision')
      uses: ./plugin-Freetalk/.github/workflows/gradle.yml
