# Runs Freetalk's CI tests once every week to see if changes in the surrounding software
# environment, e.g. Ubuntu/Windows/MacOS, broke anything.
# Running every once in a while also ensures we catch breakage which happens infrequently due to
# the randomization we use in some unit tests.
# NOTICE: This only runs on xor-freenet's repository currently, see the comment below.
name: CI cronjobs, weekly

on:
  schedule:
    - cron: 12 18 * * 1 # At 18:12 on Monday

jobs:
  weekly-ci-workflow:
    # See cron-daily.yml for comments on why this only runs on xor-freenet's repo.
    name: Weekly CI test, on xor-freenet's repo only
    if: github.repository == 'xor-freenet/plugin-Freetalk'
    uses: ./.github/workflows/gradle.yml
